In [50]:
import pandas as pd
from typing import *
rdeep= pd.read_csv("C:/Users/Alexd/Desktop/shade_shennanigans/dataset_rdeep_1.csv")
print(rdeep.columns)
# C:\Users\Alexd\Desktop\shade_shennanigans
print(rdeep.shape)


Index(['suit_opponent', 'value_opponent', 'trump_suit', 'stance_self',
       'stance_opponent', 'relative_stance', 'best_move_suit',
       'best_move_value', 'best_move_marriage', 'best_move_trump_exchange',
       'possible_M', 'possible_TE', 'move_1', 'move_2', 'move_3', 'move_4',
       'move_5', 'move_6', 'move_7', 'move_8', 'best_move', ' best_move_suit',
       'best_move_value.1'],
      dtype='object')
(9261, 23)


In [51]:
rdeep.head()

suit_opponent  value_opponent trump_suit  stance_self  stance_opponent  \
0           NaN             NaN   DIAMONDS            0                0   
1      DIAMONDS            10.0   DIAMONDS            0                0   
2           NaN             NaN   DIAMONDS           12                0   
3        SPADES            11.0   DIAMONDS            0               12   
4           NaN             NaN   DIAMONDS           13               12   

   relative_stance best_move_suit best_move_value  best_move_marriage  \
0             0.50       DIAMONDS        DIAMONDS               False   
1             0.50          CLUBS           CLUBS               False   
2             1.00         SPADES          SPADES               False   
3             1.00       DIAMONDS        DIAMONDS               False   
4             0.52          CLUBS           CLUBS               False   

   best_move_trump_exchange  ...                             move_2  \
0                     False  ...  RegularMove(card=Card.ACE_SPADES)   
1                     False  ...   RegularMove(card=Card.ACE_CLUBS)   
2                     False  ...  RegularMove(card=Card.ACE_HEARTS)   
3                     False  ...   RegularMove(card=Card.ACE_CLUBS)   
4                     False  ...  RegularMove(card=Card.TEN_HEARTS)   

                                 move_3                                move_4  \
0    RegularMove(card=Card.QUEEN_CLUBS)     RegularMove(card=Card.ACE_HEARTS)   
1  RegularMove(card=Card.JACK_DIAMONDS)  RegularMove(card=Card.KING_DIAMONDS)   
2    RegularMove(card=Card.QUEEN_CLUBS)    RegularMove(card=Card.KING_HEARTS)   
3   RegularMove(card=Card.QUEEN_HEARTS)     RegularMove(card=Card.TEN_HEARTS)   
4   RegularMove(card=Card.QUEEN_HEARTS)    RegularMove(card=Card.KING_SPADES)   

                                 move_5 move_6 move_7 move_8  \
0    RegularMove(card=Card.KING_HEARTS)    NaN    NaN    NaN   
1   RegularMove(card=Card.QUEEN_HEARTS)    NaN    NaN    NaN   
2     RegularMove(card=Card.ACE_SPADES)    NaN    NaN    NaN   
3  RegularMove(card=Card.KING_DIAMONDS)    NaN    NaN    NaN   
4  RegularMove(card=Card.KING_DIAMONDS)    NaN    NaN    NaN   

                              best_move   best_move_suit  best_move_value.1  
0   RegularMove(card=Card.TEN_DIAMONDS)         DIAMONDS                 10  
1     RegularMove(card=Card.JACK_CLUBS)            CLUBS                  2  
2     RegularMove(card=Card.ACE_SPADES)           SPADES                 11  
3  RegularMove(card=Card.JACK_DIAMONDS)         DIAMONDS                  2  
4      RegularMove(card=Card.ACE_CLUBS)            CLUBS                 11  

[5 rows x 23 columns]

In [98]:

from sklearn import datasets
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder # Appears to not be needed
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn import svm


In [86]:
LE = LabelEncoder()
another_LE = LabelEncoder()
#Let's create the feature and label sets
features: List[str] = list(rdeep.columns)
for feature in ['best_move', ' best_move_suit',
       'best_move_value.1']:
       features.remove(feature)

feature_set = rdeep[features].values
label_set = rdeep[['best_move']].values


# And here we encode the feature_set and label set
for i in range(len(feature_set[0])):
       feature_set[:,i] = LE.fit_transform(feature_set[:,i])

for i in range(len(label_set[0])):
       label_set[:,i] = another_LE.fit_transform(label_set[:,i])

print(feature_set)
print(label_set)


[[4 5 0 ... 23 0 0]
 [1 3 0 ... 23 0 0]
 [4 5 0 ... 23 0 0]
 ...
 [0 4 0 ... 23 0 0]
 [4 5 0 ... 23 0 0]
 [0 3 0 ... 23 0 0]]
[[20]
 [7]
 [6]
 ...
 [5]
 [19]
 [21]]


In [87]:
train_x, test_x, train_y, test_y = train_test_split(feature_set, label_set)

In [99]:
from sklearn.neighbors import KNeighborsClassifier
ml_bot = svm.SVC()
train_y = train_y.astype('int')
ml_bot.fit(train_x, train_y.ravel())

SVC()

In [107]:
import numpy as np
print(ml_bot.predict(test_x))
print(test_y)
pred = ml_bot.predict(test_x)
print(accuracy_score(test_y, np.argmax(pred, axis=1)))
# np.argmax(pred_train, axis=1)

[20 12  8 ... 16  4  7]
[[12]
 [11]
 [17]
 ...
 [13]
 [6]
 [10]]


AxisError: axis 1 is out of bounds for array of dimension 1